create table search_users_data (
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	email VARCHAR(255),
	phone_number VARCHAR(255),
	hire_date VARCHAR(255),
	job_title VARCHAR(255),
	salary VARCHAR(255),
	department VARCHAR(255),
	date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (1, 'Zondra', 'Rosa', 'zrosa0@simplemachines.org', '327-854-9298', '3/3/2024', 'Health Coach III', 79, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (2, 'Francesco', 'Wales', 'fwales1@house.gov', '951-512-1050', '2/7/2024', 'Senior Sales Associate', 89, 'Marketing');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (3, 'Des', 'Baskett', 'dbaskett2@sakura.ne.jp', '515-369-7830', '12/18/2023', 'Chief Design Engineer', 33, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (4, 'Adelice', 'Zanicchelli', 'azanicchelli3@chicagotribune.com', '274-630-2033', '9/7/2024', 'GIS Technical Architect', 84, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (5, 'Cordie', 'Bees', 'cbees4@blinklist.com', '464-685-5841', '11/6/2024', 'Technical Writer', 35, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (6, 'Lindsey', 'Girth', 'lgirth5@newsvine.com', '144-853-6893', '7/30/2024', 'Nurse', 78, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (7, 'Carlo', 'Middiff', 'cmiddiff6@newyorker.com', '338-862-1626', '10/1/2024', 'Programmer Analyst I', 52, 'Business Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (8, 'Tobias', 'Poppy', 'tpoppy7@flickr.com', '316-732-7028', '1/14/2024', 'Occupational Therapist', 36, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (9, 'Fawne', 'Richarson', 'fricharson8@umn.edu', '291-181-7697', '6/7/2024', 'Community Outreach Specialist', 60, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (10, 'Steffane', 'Broadfield', 'sbroadfield9@flickr.com', '636-926-5705', '12/27/2023', 'Executive Secretary', 47, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (11, 'Shelley', 'Jura', 'sjuraa@netvibes.com', '684-903-8066', '6/14/2024', 'Help Desk Operator', 72, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (12, 'Jozef', 'Pencot', 'jpencotb@psu.edu', '109-633-4083', '8/5/2024', 'Safety Technician III', 67, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (13, 'Tristan', 'Roskruge', 'troskrugec@dailymotion.com', '493-542-0066', '8/12/2024', 'Compensation Analyst', 46, 'Services');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (14, 'Noe', 'Cracknall', 'ncracknalld@bandcamp.com', '710-691-6916', '6/5/2024', 'Research Associate', 45, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (15, 'Alisha', 'Whife', 'awhifee@networkadvertising.org', '904-760-3708', '8/13/2024', 'Assistant Media Planner', 29, 'Research and Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (16, 'Luigi', 'Marguerite', 'lmargueritef@bluehost.com', '540-171-2294', '9/8/2024', 'Actuary', 62, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (17, 'Silas', 'Beacon', 'sbeacong@so-net.ne.jp', '861-317-6287', '6/23/2024', 'Associate Professor', 95, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (18, 'Edna', 'Lafee', 'elafeeh@bravesites.com', '252-809-8247', '1/23/2024', 'Budget/Accounting Analyst I', 24, 'Services');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (19, 'Sergent', 'Hamshar', 'shamshari@wix.com', '304-689-5728', '3/8/2024', 'Nurse', 85, 'Services');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (20, 'Dona', 'Woodwing', 'dwoodwingj@fc2.com', '159-362-3590', '11/12/2024', 'Nuclear Power Engineer', 72, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (21, 'Myrtle', 'Dries', 'mdriesk@ihg.com', '125-366-0931', '12/19/2023', 'VP Quality Control', 3, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (22, 'Karna', 'Pattesall', 'kpattesalll@abc.net.au', '285-630-1690', '11/20/2024', 'Payment Adjustment Coordinator', 34, 'Business Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (23, 'Aubree', 'Sussems', 'asussemsm@si.edu', '236-827-4284', '1/1/2024', 'Chief Design Engineer', 72, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (24, 'Nye', 'Lyngsted', 'nlyngstedn@arstechnica.com', '746-604-8125', '7/18/2024', 'Food Chemist', 28, 'Research and Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (25, 'Shalne', 'Bompass', 'sbompasso@thetimes.co.uk', '497-844-5976', '9/27/2024', 'Senior Financial Analyst', 16, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (26, 'Kara', 'Rimell', 'krimellp@prlog.org', '858-234-6523', '2/24/2024', 'Compensation Analyst', 20, 'Services');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (27, 'Irina', 'Eldred', 'ieldredq@goo.gl', '229-899-0087', '9/14/2024', 'Account Representative II', 14, 'Research and Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (28, 'Sargent', 'Knoles', 'sknolesr@qq.com', '978-353-6013', '8/17/2024', 'Electrical Engineer', 23, 'Human Resources');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (29, 'Reagen', 'Mc Comb', 'rmccombs@netlog.com', '274-859-5998', '5/12/2024', 'Biostatistician III', 59, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (30, 'Loutitia', 'Folks', 'lfolkst@linkedin.com', '687-557-5264', '6/2/2024', 'Programmer III', 61, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (31, 'Franciskus', 'Scotchmur', 'fscotchmuru@miitbeian.gov.cn', '645-108-8239', '5/11/2024', 'Research Assistant III', 29, 'Business Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (32, 'Fons', 'Wadge', 'fwadgev@theatlantic.com', '843-126-6737', '10/28/2024', 'Programmer III', 1, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (33, 'Wyn', 'Moscon', 'wmosconw@lycos.com', '902-986-7847', '11/20/2024', 'Automation Specialist III', 87, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (34, 'Montgomery', 'Perroni', 'mperronix@instagram.com', '447-681-2694', '4/20/2024', 'VP Product Management', 65, 'Engineering');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (35, 'Belia', 'Shorie', 'bshoriey@uiuc.edu', '153-285-5353', '7/12/2024', 'Senior Financial Analyst', 35, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (36, 'Starr', 'Brislawn', 'sbrislawnz@desdev.cn', '505-701-3918', '12/8/2023', 'Geological Engineer', 17, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (37, 'Andrey', 'Ebden', 'aebden10@ovh.net', '454-791-8103', '10/1/2024', 'Senior Sales Associate', 8, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (38, 'Jayme', 'Semble', 'jsemble11@globo.com', '545-676-2792', '12/4/2023', 'Registered Nurse', 3, 'Business Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (39, 'Danette', 'Chipping', 'dchipping12@netscape.com', '137-722-5211', '2/8/2024', 'Account Executive', 100, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (40, 'Lian', 'Flowers', 'lflowers13@ucsd.edu', '578-143-9262', '5/28/2024', 'Business Systems Development Analyst', 93, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (41, 'Deck', 'Hurleston', 'dhurleston14@xrea.com', '751-935-6417', '5/21/2024', 'Dental Hygienist', 53, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (42, 'Nelia', 'Durdle', 'ndurdle15@tinypic.com', '460-190-2789', '5/5/2024', 'VP Quality Control', 81, 'Marketing');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (43, 'Tori', 'Buckenhill', 'tbuckenhill16@umich.edu', '202-267-8328', '9/21/2024', 'Budget/Accounting Analyst III', 95, 'Services');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (44, 'Bevin', 'Fallow', 'bfallow17@wikipedia.org', '674-917-8409', '3/6/2024', 'Compensation Analyst', 42, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (45, 'Granville', 'Bernier', 'gbernier18@t.co', '397-287-4060', '2/21/2024', 'Registered Nurse', 86, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (46, 'Bree', 'Dwerryhouse', 'bdwerryhouse19@omniture.com', '247-636-8690', '6/27/2024', 'Software Test Engineer III', 9, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (47, 'Amara', 'Trivett', 'atrivett1a@tuttocitta.it', '716-911-1940', '4/28/2024', 'Analog Circuit Design manager', 41, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (48, 'Gizela', 'Clubbe', 'gclubbe1b@businessinsider.com', '696-874-7995', '2/17/2024', 'Senior Sales Associate', 32, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (49, 'Ariadne', 'Pickston', 'apickston1c@mlb.com', '857-509-9623', '7/2/2024', 'Senior Financial Analyst', 62, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (50, 'Kippy', 'Reeveley', 'kreeveley1d@about.me', '384-443-4575', '5/7/2024', 'Senior Developer', 4, 'Services');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (51, 'Locke', 'Colleymore', 'lcolleymore1e@who.int', '107-839-2640', '6/4/2024', 'Social Worker', 85, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (52, 'Trudie', 'Mersh', 'tmersh1f@wiley.com', '825-763-7868', '3/2/2024', 'Automation Specialist IV', 93, 'Human Resources');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (53, 'Mitch', 'Newbegin', 'mnewbegin1g@uol.com.br', '970-305-8933', '6/3/2024', 'Food Chemist', 94, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (54, 'Melisa', 'Drakeford', 'mdrakeford1h@go.com', '350-383-3524', '11/29/2023', 'Budget/Accounting Analyst III', 93, 'Human Resources');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (55, 'Stanwood', 'Ziebart', 'sziebart1i@ibm.com', '585-749-7464', '4/4/2024', 'Senior Sales Associate', 45, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (56, 'Raymund', 'Worvell', 'rworvell1j@berkeley.edu', '212-371-6319', '10/17/2024', 'Librarian', 57, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (57, 'Justina', 'Klimek', 'jklimek1k@naver.com', '142-228-3758', '11/20/2024', 'Office Assistant IV', 93, 'Business Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (58, 'Hart', 'Gilderoy', 'hgilderoy1l@un.org', '114-768-0030', '3/18/2024', 'Operator', 35, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (59, 'Toby', 'Paulmann', 'tpaulmann1m@dropbox.com', '529-435-6898', '10/12/2024', 'Administrative Assistant III', 57, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (60, 'Ingaborg', 'Halhead', 'ihalhead1n@uol.com.br', '652-176-2420', '5/16/2024', 'Developer II', 93, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (61, 'Rene', 'Desbrow', 'rdesbrow1o@amazon.com', '523-935-3957', '10/24/2024', 'Analyst Programmer', 8, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (62, 'Susannah', 'Cummine', 'scummine1p@ca.gov', '785-453-1688', '2/28/2024', 'Project Manager', 72, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (63, 'Hadlee', 'Grimsdike', 'hgrimsdike1q@opera.com', '467-390-3283', '3/28/2024', 'Assistant Manager', 25, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (64, 'Dyann', 'Pollock', 'dpollock1r@example.com', '250-233-5680', '9/20/2024', 'Actuary', 42, 'Business Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (65, 'Boonie', 'Gallandre', 'bgallandre1s@miibeian.gov.cn', '865-643-5925', '11/29/2023', 'Executive Secretary', 87, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (66, 'Marissa', 'Seman', 'mseman1t@hao123.com', '839-831-4446', '4/25/2024', 'Junior Executive', 93, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (67, 'Rogers', 'Scoon', 'rscoon1u@techcrunch.com', '710-696-8669', '1/18/2024', 'Web Developer I', 68, 'Services');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (68, 'Dorothea', 'Elham', 'delham1v@creativecommons.org', '863-208-6766', '4/11/2024', 'Financial Analyst', 81, 'Human Resources');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (69, 'Lock', 'Bramwich', 'lbramwich1w@dagondesign.com', '843-479-5757', '12/28/2023', 'Analyst Programmer', 68, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (70, 'Aubrey', 'Krysiak', 'akrysiak1x@umn.edu', '656-809-6008', '11/28/2023', 'Assistant Manager', 55, 'Business Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (71, 'Bryn', 'Ikins', 'bikins1y@prweb.com', '846-764-5762', '1/30/2024', 'Environmental Specialist', 46, 'Marketing');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (72, 'Neville', 'Yallop', 'nyallop1z@topsy.com', '230-344-1066', '9/6/2024', 'Editor', 35, 'Marketing');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (73, 'Fonsie', 'Larvin', 'flarvin20@freewebs.com', '323-114-5814', '4/18/2024', 'Help Desk Technician', 64, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (74, 'Kimmie', 'Swindley', 'kswindley21@forbes.com', '237-570-1691', '9/13/2024', 'Budget/Accounting Analyst I', 23, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (75, 'Riordan', 'Fatkin', 'rfatkin22@irs.gov', '871-335-0302', '10/29/2024', 'Environmental Specialist', 86, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (76, 'Kim', 'Lambie', 'klambie23@1und1.de', '814-420-1065', '7/3/2024', 'GIS Technical Architect', 80, 'Human Resources');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (77, 'Steffane', 'Ramel', 'sramel24@salon.com', '307-493-2134', '10/3/2024', 'Account Representative I', 17, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (78, 'Worthington', 'Baistow', 'wbaistow25@ebay.co.uk', '594-208-0387', '2/21/2024', 'Research Associate', 74, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (79, 'Skyler', 'Giannini', 'sgiannini26@google.com.br', '903-748-0540', '7/17/2024', 'Teacher', 76, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (80, 'Zenia', 'Dovydenas', 'zdovydenas27@ebay.co.uk', '672-577-7342', '2/11/2024', 'Software Engineer III', 92, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (81, 'Rebeca', 'Rittelmeyer', 'rrittelmeyer28@jimdo.com', '574-501-0631', '9/30/2024', 'Paralegal', 43, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (82, 'Kalle', 'Strank', 'kstrank29@behance.net', '651-987-2858', '5/8/2024', 'Analog Circuit Design manager', 49, 'Engineering');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (83, 'Paola', 'Croydon', 'pcroydon2a@cbslocal.com', '612-106-3698', '4/18/2024', 'Occupational Therapist', 70, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (84, 'Brana', 'Scarrisbrick', 'bscarrisbrick2b@blogtalkradio.com', '969-266-9829', '12/24/2023', 'Administrative Assistant I', 66, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (85, 'Avram', 'Fears', 'afears2c@msn.com', '482-854-6606', '2/25/2024', 'Computer Systems Analyst III', 51, 'Marketing');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (86, 'Anna', 'Skeemor', 'askeemor2d@nationalgeographic.com', '312-953-7591', '10/22/2024', 'Recruiting Manager', 20, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (87, 'Cedric', 'Lumby', 'clumby2e@amazon.co.uk', '922-506-6536', '4/24/2024', 'Marketing Assistant', 50, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (88, 'Wallache', 'Ratley', 'wratley2f@dailymail.co.uk', '197-538-4066', '6/8/2024', 'Software Consultant', 93, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (89, 'Bret', 'Tantrum', 'btantrum2g@weebly.com', '156-431-1728', '1/31/2024', 'Geological Engineer', 31, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (90, 'Kiley', 'Foulser', 'kfoulser2h@unesco.org', '372-975-2873', '5/11/2024', 'Geologist II', 1, 'Legal');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (91, 'Kellia', 'Jerke', 'kjerke2i@printfriendly.com', '753-110-8083', '4/24/2024', 'Project Manager', 16, 'Research and Development');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (92, 'Clarissa', 'Lorkings', 'clorkings2j@mozilla.com', '829-794-0002', '7/30/2024', 'Marketing Manager', 56, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (93, 'Sheffie', 'Roust', 'sroust2k@state.gov', '855-112-8362', '7/18/2024', 'Social Worker', 44, 'Training');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (94, 'Derry', 'Dzenisenka', 'ddzenisenka2l@photobucket.com', '450-157-0958', '1/6/2024', 'Software Engineer II', 96, 'Accounting');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (95, 'Eadith', 'Speerman', 'espeerman2m@goo.gl', '684-701-3521', '6/17/2024', 'Payment Adjustment Coordinator', 17, 'Engineering');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (96, 'Godfrey', 'Wayper', 'gwayper2n@ihg.com', '184-368-6549', '10/19/2024', 'Environmental Tech', 81, 'Sales');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (97, 'Franciska', 'Stennes', 'fstennes2o@topsy.com', '644-556-0498', '3/14/2024', 'Professor', 45, 'Support');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (98, 'Nowell', 'Wakerley', 'nwakerley2p@intel.com', '938-827-9421', '10/17/2024', 'Human Resources Assistant II', 56, 'Marketing');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (99, 'Margaretta', 'Landreth', 'mlandreth2q@github.io', '612-428-2931', '7/24/2024', 'Cost Accountant', 32, 'Product Management');
insert into search_users_data (id, first_name, last_name, email, phone_number, hire_date, job_title, salary, department) values (100, 'Westley', 'Briggs', 'wbriggs2r@sphinn.com', '326-231-1721', '2/1/2024', 'Assistant Manager', 79, 'Business Development');